/* ===========================================================================
   Starfall Atlas — region data + geometry
   ---------------------------------------------------------------------------
   The world map is one gapless tessellation on a 1600×1200 field. Each region
   carries: heraldic house metadata, a sector designation (intel-map flavour),
   lore, the main-map polygon, a label anchor, and a self-contained SUBMAP made
   of smaller interlocking districts (its own 1000×760 field).

   Submap districts are generated by `pinwheel()` — it splits an irregular hull
   into four interlocking cells around a shared interior node, so the children
   always tile without seams. The Grounds uses a 3-cell variant.
   =========================================================================== */
(function () {
  // p("x,y x,y ...") -> "x,y x,y" passthrough; kept for readability of literals.
  const P = (s) => s.trim();

  /* Split a quad hull [TL,TR,BR,BL] into 4 interlocking cells around interior
     node C, using edge nodes mt (top), mr (right), mb (bottom), ml (left).
     Returns 4 point-strings sharing exact coordinates on every internal seam. */
  function pinwheel(TL, TR, BR, BL, C, mt, mr, mb, ml) {
    const j = (pts) => pts.map((p) => p[0] + "," + p[1]).join(" ");
    return [
      j([TL, mt, C, ml]), // top-left cell
      j([mt, TR, mr, C]), // top-right cell
      j([C, mr, BR, mb]), // bottom-right cell
      j([ml, C, mb, BL]), // bottom-left cell
    ];
  }

  const REGIONS = [
    /* ---- AMBER WOODS — forest, Boar House ------------------------------ */
    {
      id: "amber-woods",
      name: "Amber Woods",
      house: "Boar House",
      crest: "boar",
      house_color: "forest",
      sector: "SECTOR I",
      coord: "61°N · 12°W",
      tagline: "The old canopy",
      blurb:
        "The endless expanse of deep forest that sprawls out to the north of campus, full of ancient ley magic, beasts and fey, and old, forgotten secrets. Home to Boar House, herbalists, bestiologists, and cottagecore influencers.",
      facts: [
        ["House seat", "Boar House"],
        ["Terrain", "Vast woodlands"],
      ],
      points: P("300,300 820,210 1230,230 1130,470 800,400 800,660 640,620 470,560 190,500"),
      label: [560, 400],
      submap: {
        view: [1000, 760],
        outline: "130,170 380,95 660,110 880,200 925,420 840,620 560,690 280,665 120,500 75,330",
        subPos: { A:[474,521,0,1], B:[539,137,0,1], C:[770,450,0,1], D:[565,520,0,1], E:[89,440,0,1] },
        subLabel: { A:[2,42], B:[-58,0], C:[37,-25], D:[-4,-10] },
        subs: [
          { name: "Boar House", blurb: "A Tudor-style complex in forest green and brick red, this House sprawls out wide and nestles in naturally with the surrounding woods. Cozy, friendly, and welcoming, Boar House always smells like food and sounds like laughter." },
          { name: "Deep Woods", blurb: "The woods extend well past the point of safety, plunging into uncharted territory beyond the wards, where fey and beasts rule. Many ancient shamanic civilizations have risen and fallen in these woods, but the trees keep their secrets." },
          { name: "Wild Areas", blurb: "The wards provide a graded protective mechanism, allowing progressively more dangerous creatures into the wild areas the deeper one goes. This means if you need to find a wild chimera, you can do so without getting jumped by a scale giant." },
          { name: "Creature Grounds", blurb: "Many areas around the woods are natural sanctuaries designed to nurture magical creatures, both for preservation and for bestiological study. Or just to have them there so you can go pet them. Expect to make a galobalo friend." },
          { name: "Herbalist Sanctuaries", blurb: "Greenhouses, gardens, and wild nature preserves maintain and protect all manner of magical plants in these areas that can be found all over the woods." },
        ],
      },
    },

    /* ---- RYKER CLIFFS — crimson, Eagle House --------------------------- */
    {
      id: "ryker-cliffs",
      name: "Ryker Cliffs",
      house: "Eagle House",
      crest: "eagle",
      house_color: "crimson",
      sector: "SECTOR II",
      coord: "58°N · 03°E",
      tagline: "The eastern reach",
      blurb:
        "These cliffs transition quickly, from lush alpine peaks filled with mountainous creatures, into the imposing structure of Eagle House, and then rapidly into inhospitable crags like dragon’s fangs. The harsh terrain of the cliffs hides countless secrets and abandoned places.",
      facts: [
        ["House seat", "Eagle House"],
        ["Terrain", "Rocky cliffs"],
      ],
      points: P("1230,230 1470,430 1500,760 1330,1040 1120,1000 1230,860 1150,770 1130,470"),
      label: [1320, 560],
      submap: {
        view: [1000, 760],
        outline: "130,170 380,95 660,110 880,200 925,420 840,620 560,690 280,665 120,500 75,330",
        subPos: { A:[320,250,4,1], B:[318,433,27,1], C:[587,100,0,1], D:[604,449,0,1], E:[561,452,0,1] },
        subLabel: { B:[-4,23], C:[0,-21], D:[21,-29], E:[0,-19] },
        subs: [
          { name: "Eagle House", blurb: "High in the cliffs overlooking campus, Eagle House stands guard, a castle-like building in gray stone that opens into interiors that evoke sweeping Romanticism. Its observation spires, promenades, and terraces provide unbeatable views of Starfall, but like its students, it seems cold and aloof from the outside." },
          { name: "Stone Steppes", blurb: "The cliffs don’t rise sharply but instead roll off in layers, each with its own ecosystem, more wild and magical the higher they go. Many small cave networks, hidden buildings, and beast nests lie in wait among the trees and rocky overhangs of these cliffs." },
          { name: "Wild Cliffs", blurb: "Beyond Eagle House is where the cliffs become harsh and unruly, like the world telling you to stay away. Bare rock faces drive into snarling spires and jagged crags, and chaotic magic from unstable ley line outcroppings can make even experienced arcanists spark out in these environs. But for those willing to brave it, powerful and innovative magic is rife here." },
          { name: "Workshops", blurb: "Owing to the powerful and chaotic magic in the cliffs, many arcane workshops have sprung up in remote locations over the centuries—and owing to the powerful and chaotic magic, few of them have survived the test of time. Anyone wandering the cliffs is likely to find an abandoned workshop eventually, which can be dangerous, especially if it’s not abandoned anymore." },
          { name: "Eagle’s Flight", blurb: "The road up to Eagle House is populated with small outposts where a student might stop for a bite to eat on a terrace with the wind in their hair, or to peruse a popup shop for some magic materials someone’s just found from searching the cliffs. While many students opt to skip the daily cliff climb and take wyvern cars instead, others insist the spontaneous discovery of Eagle’s Flight can’t be replaced." },
        ],
      },
    },

    /* ---- JEWELSTONE HOLLOW — plum, Dragon House ------------------------ */
    {
      id: "jewelstone-hollow",
      name: "Jewelstone Hollow",
      house: "Dragon House",
      crest: "dragon",
      house_color: "plum",
      sector: "SECTOR III",
      coord: "55°N · 06°W",
      tagline: "The deep seams",
      blurb:
        "The sharp crags of this region are rich with magic, and Dragon House lies nestled among the cemeteries and gravewood trees that fill this place, and the jagged wings of dragons fill the sky.",
      facts: [
        ["House seat", "Dragon House"],
        ["Terrain", "Enchanted stony outcroppings"],
      ],
      points: P("800,400 1130,470 1150,770 800,660"),
      label: [1000, 575],
      submap: {
        view: [1000, 760],
        outline: "130,170 380,95 660,110 880,200 925,420 840,620 560,690 280,665 120,500 75,330",
        subPos: { A:[496,548,4,1], B:[742,475,-16,1], C:[426,456,0,1], D:[561,520,-60,1], E:[383,439,11,1] },
        subLabel: { A:[0,10], B:[6,10], C:[4,-29], D:[8,15], E:[0,-15] },
        subs: [
          { name: "Dragon House", blurb: "A dark Gothic structure with dramatic flying buttresses and tall stained-glass windows, the House is exactly as imposing as its people, projecting power in everything. More so than even the other Houses, Dragon House holds secrets untold behind hidden passages and secret chambers." },
          { name: "Onyx Rock", blurb: "The dramatic stone imbued with draconic magic that stands like a silent sentinel over Dragon House, dragons are always nesting among these rocks, and seeing wyrms and wyverns dive from its edge is an everyday sight for the students of Dragon House." },
          { name: "Cemeteries", blurb: "Jewelstone Hollow’s solemn atmosphere and latent necromantic magics make it the perfect place for cemeteries, and not just for humans: many draconic creatures inter their dead in the Hollow as well, and it’s common to find cemeteries both large and small." },
          { name: "Abyssal Valley", blurb: "Carving out a long, thin path that snakes through the depths of the Hollow around Dragon House’s cliffs, the Abyssal Valley has its lowest levels tinged with demonic magic, and many ancient things here have been breached by demonic entities from before the interplanar compact. Proceed with caution." },
          { name: "Stonehaven", blurb: "The quieter areas of the Hollow, Stonehaven is home to many esteemed and lofty faculty homes, possibly the most coveted address outside the Citadel. Great manors peek out from between the gravewood trees, and some more esteemed class halls and facilities are here too." },
        ],
      },
    },

    /* ---- GLIMMERDEEP LAKE — teal, Dolphin House ------------------------ */
    {
      id: "glimmerdeep-lake",
      name: "Glimmerdeep Lake",
      house: "Dolphin House",
      crest: "dolphin",
      house_color: "teal",
      sector: "SECTOR IV",
      coord: "53°N · 14°W",
      tagline: "The bright water",
      blurb:
        "Relatively tranquil compared to the rest of the Academy, that’s only because most of the magic is below the surface here, whether the buried Old House underneath Dolphin House, or the ancient creatures that dwell deep in the lake. The lake’s scenic backdrop and sapphire-blue waters make it popular both for picnic dates and dramatic duel backgrounds.",
      facts: [
        ["House seat", "Dolphin House"],
        ["Terrain", "Sapphire-blue waters"],
      ],
      points: P("190,500 470,560 640,620 520,790 700,970 520,1040 210,820"),
      label: [375, 760],
      submap: {
        view: [1000, 760],
        outline: "130,170 380,95 660,110 880,200 925,420 840,620 560,690 280,665 120,500 75,330",
        subPos: { A:[582,373,-49,1], B:[374,370,0,1], C:[344,396,0,1], D:[465,176,0,1], E:[621,472,0,1] },
        subLabel: { A:[0,8], D:[44,35], E:[2,21] },
        subs: [
          { name: "Dolphin House", blurb: "The sleek modern designs of Dolphin House on the water conceal something darker underneath: the Old House, destroyed decades ago, but parts of it still linger underground, off-limits fey territory now. The House is organized around its twelve Constellation Halls, one for each Zodiac sign, usually each filled with a party, making the whole thing a metaphor for its students: pretty on the outside, sometimes deceptive under the surface, and always ready for a party." },
          { name: "The Lake", blurb: "Glimmerdeep Lake itself is a surprisingly deep channel of water that runs out to the ocean eventually, facilitating the long journeys of water wyrms who make a scene when they arrive at Starfall. Even the Academy’s oldest and most experienced arcanists don’t have any idea what secrets lie within the lake’s depths, but its magic is undeniable: potions made with a base of Glimmerdeep waters are regarded the world around as the gold standard." },
          { name: "Tributaries", blurb: "Beyond the main body of the lake lie countless rivers and streams broken up by the low hills and the woods beyond, and many of them run through surprisingly deep chasms themselves, often containing countless magical secrets." },
          { name: "Lakewood", blurb: "The woods that close in around Glimmerdeep and the space beyond are often gentler than the depths of Amber Woods, and make for popular hiking. Many hidden gems well-loved by the few arcanists who know about them lie between the rivers and coves of Glimmerdeep Lake’s reaches." },
          { name: "The Banks", blurb: "The soft grass at the water’s edge makes one of the most peaceful places in Starfall, whether by morning to watch the sunrise break over the cliffs and light the lake orange, all the way to the depths of night when the stars reflect on the lake’s surface and Dolphin House lights up in illusion magic against the darkness. A popular place for picnics, dates, or just somebody to get away from it all." },
        ],
      },
    },

    /* ---- THE GROUNDS — light green, intermediary ----------------------- */
    {
      id: "the-grounds",
      name: "The Grounds",
      house: "Common Ward",
      crest: "lines",
      house_color: "meadow",
      sector: "SECTOR V",
      coord: "54°N · 09°W",
      tagline: "The shared green",
      blurb:
        "Everything that lies beyond the Citadel's walls is known as the Grounds, the open spaces filled with natural magic that stretches from Glimmerdeep Lake's farthest river reaches to the distant peaks of Ryker Cliffs. The area directly around the Citadel is common ground, with every House crossing it to reach the Citadel, and plenty of its own magics.",
      facts: [
        ["Holding", "Common Ward"],
        ["Terrain", "Meadows and groves"],
      ],
      points: P("640,620 800,660 1150,770 1230,860 1120,1000 920,1090 520,1040 700,970 520,790"),
      label: [1055, 878],
      submap: {
        view: [1000, 760],
        outline: "130,170 380,95 660,110 880,200 925,420 840,620 560,690 280,665 120,500 75,330",
        subPos: { A:[716,265,-22,1], B:[587,275,-100,1], C:[314,169,-33,1], D:[374,620,16,1], E:[660,436,-18,1] },
        subLabel: { A:[31,21], B:[-8,-6], C:[23,0], D:[-35,0] },
        subs: [
          { name: "Millennium Tower", blurb: "The tallest building in Starfall, Millennium Tower stands sentinel from the border of Jewelstone Hollow, a symbol of magic rising up from Lumine Field. Some classes are held here, but Millennium Tower is primarily used by faculty and researchers, the proximity to Lumine Field helping study particular magic reactions." },
          { name: "Lumine Field", blurb: "According to ancient legend, the falling star that birthed magic landed right here in Lumine Field and sprouted into the Wishing Tree that stands here. The whole “falling star that birthed magic” thing is just a fairy tale, but the Wishing Tree is a one-of-a-kind magic plant that draws from the convergence of ley lines underneath Lumine Field, and it’s believed that this very natural phenomenon is what led to folklore about the falling star." },
          { name: "Greenhouses", blurb: "The Grounds are an herbalist’s paradise, and the countless greenhouses and herbological centers scattered around everywhere, but especially close to Amber Woods, stand as testament to that." },
          { name: "Residential Areas", blurb: "The Grounds around the Citadel are popular for houses for those who want to still be within Starfall but can afford a little space. Two and a half kids and a white picket fence with a view of Millennium Tower is the arcanist’s dream for some." },
          { name: "Groves", blurb: "Natural magic clusters around the Grounds into small copses and groves that tend to gather small magic creatures. And where magic gathers like this, something unusual is guaranteed to be hidden. It’s not uncommon for a student to try nipping into one just out of curiosity and find themselves with an unstable artifact fished out from a pond. Proceed at your own risk." },
        ],
      },
    },

    /* ---- STARFALL CITADEL — gold, Scorpion House ----------------------- */
    {
      id: "starfall-citadel",
      name: "Starfall Citadel",
      house: "Scorpion House",
      crest: "scorpion",
      house_color: "gold",
      sector: "SEAT OF THE REALM",
      coord: "54°N · 09°W",
      tagline: "The gilded seat",
      blurb:
        "The heart of the realm and the seat of Scorpion House — a tiered fortress of gilded stone where the great hall, the observatory and the vault all stand. Every road in the world ends here.",
      facts: [
        ["House seat", "Scorpion House"],
        ["Role", "Seat of the realm"],
        ["Within", "Hall · Observatory · Vault"],
      ],
      // Shield silhouette (drawn on top of The Grounds), centred ~ (810, 800).
      isCitadel: true,
      points: P("700,690 920,690 920,830 855,930 810,975 765,930 700,830"),
      label: [810, 770],
      submap: {
        view: [1000, 1200],
        // The Citadel submap is a full heater-shield tessellation: each seed is
        // placed at its position on the mockup; app.js builds a Voronoi diagram
        // clipped to the shield outline so the 24 cells interlock gaplessly.
        shield: true,
        shieldGeom: { cx: 500, top: 80, hw: 430, h: 1040 },
        shieldOpts: { spike: 0.095, shoulder: -0.02, side: 0.40 },
        seeds: [
          // ---- 21 districts (numbered per the Citadel ledger). `color` is a
          //      muted, midnight-friendly tint loosely echoing the mockup. ----
          { name: "Marveille District", tag: "01", x: 279, y: 901, color: "oklch(0.56 0.06 12)", w: 68,
            labelDx: 36, labelDy: 61,
            blurb: "Marveille District, typically just Marveille, is the commercial center of the Citadel, set at the base together with the Great Hall. You’ll find countless shops, beautiful side streets with enchanted draperies that run over the Juliette balconies from second-floor apartments, and music on every corner. Marveille Station is Starfall’s connection to the outside world.",
            subPos: { A:[353,479,0,1], B:[608,518,-23,1], C:[457,2,0,1], D:[344,466,0,1], E:[569,492,0,0], F:[695,470,0,1] },
            subGen: { D: "Residential", F: "Commercial" },
            subLabel: { B:[10,21], C:[-23,15], D:[0,-17], F:[-46,-94] },
            subs: [
              { name: "Marveille Station", blurb: "The transit hub connecting Starfall Citadel to the rest of the world, with enchanted streetcars that run through Marveille and to the residential areas beyond the Citadel, and with trains that link to Albany and other regions." },
              { name: "Promenade de Lune", blurb: "The most emblematic shopping street in Starfall and the heart of most festival celebrations, always lined with activity, shop barkers, and music." },
              { name: "The Grand Heron complex", blurb: "A shopping center where the ward rules are relaxed and many non-human entities do business, such as fey, lesser dragons, and breakaway summons." },
            ] },
          { name: "Astral Quarter", tag: "02", x: 400, y: 808, color: "oklch(0.50 0.07 330)", w: 46,
            labelDx: 5, labelDy: 23,
            blurb: "The Astral Quarter is well known for beautiful plazas, multi-level outdoor structures with great sculptures and enchanted water features, and some of the classier places to grab a bite to eat or a new wand. Classes here are held in beautiful symposiums and magical halls that shimmer under each footstep.",
            subPos: { A:[361,54,-81,1], B:[569,390,-52,1], C:[729,531,-51,1], D:[345,470,0,1], E:[500,492,0,1], F:[655,192,0,1] },
            subGen: { D: "Commercial", E: "Class Halls", F: "Residential" },
            subLabel: { A:[-10,0], B:[-56,-33], C:[0,15], D:[-12,0], E:[-21,-33], F:[-17,17] },
            subs: [
              { name: "Saint Juliette’s Forum", blurb: "The most prestigious enchanter’s forum in Starfall, where early-year enchanters visit just to take it in. Some of the world's greatest enchantment techniques have come from this complex." },
              { name: "Gilded Empress Square", blurb: "A picturesque plaza best suited to photographs, with the shops here being beautiful, inspiring, and entirely irrelevant to you unless you’re rich." },
              { name: "Celestial Theater", blurb: "A renowned interdisciplinary class hall with a stunning classical design and floors in parts that look like glass-bottom boats, with spectral forms that move with you as you walk." },
            ] },
          { name: "Juniper Square", tag: "03", x: 210, y: 560, color: "oklch(0.56 0.07 150)",
            labelDx: 0, labelDy: 14,
            blurb: "Juniper Square is a simple district that does what it sets out to do. The classical stonework construction that makes up most of the buildings, some of the oldest in the Citadel, establishes a quietly stately, down-to-earth atmosphere. Many hardy magic plants grow in the small wild gardens around the place, and the castle-like buildings spiral upwards in complex structures. Most buildings here are class halls: these halls hold old teachings of natural magics.",
            subPos: { A:[734,413,-31,1], B:[141,354,-64,1], C:[487,373,0,1], D:[353,470,-46,1], E:[773,298,0,1], F:[617,176,0,1] },
            subGen: { D: "Class Halls", E: "Commercial", F: "Class Halls" },
            subLabel: { A:[4,0], B:[0,19], C:[-27,-29], E:[0,25] },
            subs: [
              { name: "Dragonfall", blurb: "A large interior courtyard space where the sunlight comes filtered through feybough, and memories manifest as spectral forms here. Dragonfall is a deeply magical space said to be where the Great Dragon was once sealed away." },
              { name: "Maserat’s Overlook", blurb: "This ancient watchtower on the western wall has now become a legendary training ground and dueling spot, warmed by walls of spectral flame that reacts to the magic cast around it." },
              { name: "Eaglehunt", blurb: "Cleaving the district cleanly down the middle, rows of terraces and draping hookblossom vines hide the many small class halls and magic workshops in this area." },
            ] },
          { name: "Dragon’s Walk", tag: "04", x: 522, y: 1062, color: "oklch(0.50 0.07 158)", w: -51,
            labelDx: 0, labelDy: 29,
            blurb: "Dragon’s Walk is the district that greets you when you enter the Citadel through its main gates, and it doesn’t pretend to be anything other than a grand entryway and a great courtyard for its primary attraction, the Great Hall. Glimmering avenues lined with whisperwood trees and statuaries hide the truth of this place: Enforcers’ sigils are everywhere, making sure nobody starts a fight in the Great Hall.",
            subPos: { A:[522,242,0,1], B:[522,637,0,1], C:[522,505,0,1], D:[345,470,0,0], E:[500,492,0,0], F:[655,470,0,0] },
            subLabel: { A:[-46,17], B:[2,-17], C:[-8,0] },
            subs: [
              { name: "The Great Hall", blurb: "The heart of campus, where Starfall gathers each morning to keep their plans in motion, its magic kitchens that feed half of Starfall each day are always in need of volunteers." },
              { name: "South Gate", blurb: "Despite not being used as an entry much by students, with all the Houses being north of here, the ornate statuary of the South Gate is emblematic of the Citadel." },
              { name: "La Avenida", blurb: "Often called the Avenida or simply Avenida, this great throughway is designed to make the viewer feel small, with massive walls and statues, and even the whisperwood trees here seem bigger." },
            ] },
          { name: "Crescent District", tag: "05", x: 504, y: 314, color: "oklch(0.60 0.045 90)", w: 52,
            labelDx: -54, labelDy: -23,
            blurb: "The Crescent District is located at the highest elevation of the Citadel, where its terraces rise to the Citadel’s highest point: the great clock tower, Cloudless Tower. With transit links to the rest of the grounds via wyvern car, a thriving ecosystem of small magic businesses selling every kind of material you might need, an array of class halls focusing on spectral magics, and of course, Scorpion House itself, the Crescent District is the liveliest part of the Citadel.",
            subPos: { A:[617,337,71,1], B:[236,275,-80,1], C:[478,541,0,1], D:[345,470,0,1], E:[500,492,0,1], F:[655,470,0,1] },
            subGen: { F: "Class Halls" },
            subLabel: { B:[-15,0], C:[-27,-12], D:[-2,0], E:[19,8] },
            subs: [
              { name: "Scorpion House", blurb: "The youngest of the Five Houses, this Art Nouveau style complex prizes intricate, layered beauty, and the flowing lines of its windows spill into ornate stairwells and enchanted walkways that react to your presence." },
              { name: "Everdream", blurb: "Starfall’s only center dedicated solely to hypnomancy, Everdream is constantly shifting, with great murals that are different from day to day, feybough trees that bend to shelter you from the world when you step into a secluded room, and of course, small but ornate bedrooms for students to nap in." },
              { name: "Redmare Way", blurb: "A long, curved street where time passes slower than the outside, steeped in chronomancy and surrounded by chronomantic class halls, its many concealed terraces all have views of Cloudless Tower." },
              { name: "Sunspark Colonnade", blurb: "The highest ground-level point in the Citadel, with great walkways that overlook the rest of the Citadel around, and the network of wyvern cars that connect from here to the Grounds." },
              { name: "Cloudless Tower", blurb: "The symbol of Starfall, of chronomancy, and one of the symbols of magic itself, this old clock tower is named after the great chronomancer Harriett Cloudless, who notably didn’t want it named after her." },
            ] },
          { name: "Brewer’s Corridor", tag: "06", x: 312, y: 432, color: "oklch(0.52 0.06 178)", w: -72,
            labelDx: 5, labelDy: 14,
            blurb: "The Brewer’s Corridor punches well above its weight: despite being a small district squeezed in between the much larger Crescent District and Juniper Square, the Brewer’s Corridor does what it does well: brewing. Alchemy labs squeeze into these steep, narrow streets in old wooden buildings with colorful gables, and potion shops are everywhere. Don’t be surprised to turn a corner and find someone’s very large, very furry pet beast here.",
            subPos: { A:[509,219,0,1], B:[639,475,0,1], C:[431,521,-10,1], D:[345,470,0,1], E:[500,466,0,1], F:[543,470,0,0] },
            subGen: { D: "Residential", E: "Class Halls" },
            subLabel: { B:[15,0], C:[23,35], D:[-8,17], E:[6,-6] },
            subs: [
              { name: "Topsy-Turvy", blurb: "The highest point of the district connects to the lowest point via this lopsided building it’s easy to get lost in, where none of the doors are aligned quite right, really a collection of different buildings that grew into one another." },
              { name: "Wishbloom Tower", blurb: "An open-air alchemical center built around a great emberwood tree, with alchemy labs and small symposiums on the center’s many levels." },
              { name: "Vialbottom", blurb: "The lowest point of the district, a trough in the center, is also its least regulated, with cheap rents, shady businesses, and more brewsharks than you can count." },
            ] },
          { name: "Songwood Path", tag: "07", x: 361, y: 517, color: "oklch(0.54 0.035 72)", w: -83,
            labelDx: -7, labelDy: 14,
            blurb: "Songwood Path is primarily a residential area, a coveted address with townhouses behind magically sealed gates. Mercy Square’s redbrick spills over here and gives it a cozy feel: magic vines bursting out over brick walls and enough greenery that a pixie dragon or two will likely be watching you walk past. The handful of shops and class halls here are largely focused on restoration and artificy.",
            subPos: { A:[522,469,0,1], B:[643,396,-24,1], C:[670,250,0,1], D:[345,470,0,1], E:[500,492,0,0], F:[655,470,0,1] },
            subGen: { C: "Residential", D: "Residential", F: "Commercial" },
            subLabel: { B:[39,8], C:[56,33], D:[6,0], F:[75,-12] },
            subs: [
              { name: "The Baroness", blurb: "A small but esteemed restoration facility that holds class halls and practicals, as well as a renowned collection of original magic tomes on restoration." },
              { name: "Trundale’s Trove", blurb: "A small museum dedicated to the great magic trickster, showcasing a collection of artifacts they stole. Supposedly a monument to having stopped them, but rascals come to pay their respects." },
            ] },
          { name: "Starburn Alley", tag: "08", x: 344, y: 210, color: "oklch(0.62 0.08 122)", w: -100,
            labelDx: -16, labelDy: 36,
            blurb: "Starburn Alley marks where the terraces of the Crescent District fall off sharply towards the gardens in the north, and the views are appropriately stunning. From these buildings in glistening white that hug the terrace edges, you can see the Dragoncrest Gardens spilling out below you, and then clear on over the Grounds beyond. You can find all sorts of class halls here, along with plenty of enchanters’ labs and artificy forums. You can also find plenty of beautiful water features from glistening Glimmerdeep water routed through the Citadel and down towards the gardens below.",
            subPos: { A:[383,541,0,1], B:[340,446,0,1], C:[670,250,0,1], D:[643,393,0,1], E:[500,492,0,0], F:[655,470,0,0] },
            subGen: { D: "Class Halls" },
            subLabel: { B:[-15,8], C:[17,0], D:[19,-15] },
            subs: [
              { name: "Winterlight", blurb: "This grand but solemn magic center marks the primary entry to the twilit streets of Ravensbeak. Sitting in a class hall where one side looks out over a sunny day in the Blackwing District and the other into twilight in Ravensbeak is known to be jarring on your circadian clock." },
              { name: "Farmor’s Promenade", blurb: "An ornate walkway that runs down into the Blackwing District with small, winding streets that always seem to have a path you didn’t notice before, gold brick that occasionally rearranges itself due to unstable magics." },
              { name: "Great Dolphin’s Grace", blurb: "A renowned center for the illusory arts, this building flows like water down the terraces of Starburn Alley." },
            ] },
          { name: "Champion Forum", tag: "09", x: 677, y: 927, color: "oklch(0.50 0.012 250)", w: -18,
            labelDx: 47, labelDy: -16,
            blurb: "The Champion Forum defines the old structure of the Citadel, from before Marquez’s time shaped the Citadel as it is today. This district of austere stone and brick lies along the ancient East Wall, and make no mistake: the champion in question is Reginaeus, the Great Boar. Fittingly, the district is full of spell practice ranges, dueling grounds, and casting-heavy classes.",
            subPos: { A:[716,291,6,1], B:[284,449,0,1], C:[517,252,0,1], D:[345,470,0,1], E:[617,192,0,1], F:[504,232,0,1] },
            subGen: { D: "Class Halls", E: "Commercial", F: "Residential" },
            subLabel: { A:[15,0], B:[-6,0], C:[-17,0], D:[8,0], E:[19,-27], F:[37,-29] },
            subs: [
              { name: "The East Wall", blurb: "A relic of a time long past, these days the East Wall is a cultural symbol instead of a defensive one, old stone walls with overlooks lit by enchanted floating lanterns that makes it feel like a world apart and a great romantic walk at night." },
              { name: "Hero’s Walkway", blurb: "A long path flanked by class halls in the casting arts, striking stone spires that make for iconic duel backdrops." },
              { name: "Lower Forum", blurb: "The area close to the East Wall and down at ground level, this zone is full of enchanter’s labs, artificy halls, alchemy benches, and crystal centers." },
            ] },
          { name: "Heraldry", tag: "10", x: 872, y: 408, color: "oklch(0.46 0.02 262)",
            labelDx: 5, labelDy: 104,
            blurb: "Heraldry watches like a dark sentinel over the east of campus, with dark Gothic spires that make it clear when you’ve transitioned from sparkling Shatterstar Square to this recently-rebuilt district, under the controversial leadership of Headmaster Valdez in the 60s. Darkly beautiful with murmur trees that muffle sound into an otherworldly effect here, the district holds graveyards and heavily sealed repositories of hexological magic.",
            subPos: { A:[526,232,0,1], B:[595,551,0,1], C:[439,350,0,1], D:[539,298,0,1], E:[500,492,0,1], F:[655,470,0,0] },
            subGen: { D: "Residential", E: "Class Halls" },
            subs: [
              { name: "Argon’s Colonnade", blurb: "Filled with graveyards, mausoleums and centers of necromantic magic, the Colonnade has the weight in the air of secrets taken to the grave—and of necromancers trying to get to them anyway." },
              { name: "Towerfall Vault", blurb: "None may enter and none may leave this repository of sealed hexological magic, guarded with the most powerful wards in the Citadel." },
              { name: "Wexley Tower", blurb: "A center of summoning magic with class halls held in rooms so teeming with magic that they seem to always be at odd angles, and magic items behave strangely within its walls." },
            ] },
          { name: "Brownbark", tag: "11", x: 639, y: 252, color: "oklch(0.47 0.05 58)", w: -23,
            blurb: "Brownbark is likely the most desired address in the Citadel, with beautiful historic buildings in brown brick, breathtaking old houses, small and stately libraries and magic troves, quiet parks, and very important people, mainly owing to the Headmaster traditionally keeping their private residence here. Primarily residential, the district does have some class halls, primarily for arcane history.",
            subPos: { A:[613,495,0,1], B:[682,360,0,1], C:[474,568,0,1], D:[345,470,0,1], E:[500,492,-28,1], F:[655,470,0,1] },
            subGen: { D: "Residential", E: "Commercial", F: "Residential" },
            subLabel: { B:[23,17], C:[0,10], F:[25,0] },
            subs: [
              { name: "Del Rosario", blurb: "Often just Rosario, this old cathedral has been converted into an esteemed center of arcane history, as well as a museum of Marquez-era arcane relics." },
              { name: "Dreamwood", blurb: "A beautiful park where pixies play and galobalos tumble, centered around an old statue of the first official headmaster Magdalena Stonebrook, enchanted with soothing magics that suppresses aggression and frustration in anyone nearby, making it the perfect place to relax." },
              { name: "Seokryu Tower", blurb: "A tall, elegant building overlooking the gleaming stone of Shatterstar Square, popular with events among the Citadel’s elite." },
            ] },
          { name: "Blackwing District", tag: "12", x: 210, y: 153, color: "oklch(0.44 0.13 352)", w: -44,
            labelDx: -7, labelDy: 9,
            blurb: "The Blackwing District forms the hard, jagged northwestern corner of the Citadel, lush with draconic roosts that form naturally among the stonework and wild nature woven into the place. The Titanius Building of Draconic Studies, commonly just Titanius, is the heart of the Academy’s draconological studies, and maintains the roosts.",
            subPos: { A:[526,215,24,1], B:[331,475,0,1], C:[509,459,0,1], D:[383,459,0,1], E:[500,492,0,1], F:[721,525,0,1] },
            subGen: { D: "Class Halls", E: "Residential", F: "Residential" },
            subLabel: { A:[-85,0], C:[-12,0], D:[4,0], E:[0,2], F:[0,94] },
            subs: [
              { name: "Titanius", blurb: "The Academy’s largest draconological center, this is where all Starfall’s draconological operations take root from, and where students go to become accredited in dragon-riding." },
              { name: "Noctus", blurb: "A commercial area and the best place in the Citadel to shop for draconological supplies, many small shops here have scaleworm problems." },
              { name: "The Arena", blurb: "An unofficial name for the broad, flat portion in the center of the district, so known for its propensity for dragons to stroll around like they own the place, which inevitably means squaring up with other dragons strolling around like they own the place." },
            ] },
          { name: "Windwalk", tag: "13", x: 600, y: 612, color: "oklch(0.62 0.06 232)", w: -38,
            labelDx: 16, labelDy: 14,
            blurb: "Windwalk is a small district in the center between many important districts, serving as a throughway with many beautiful river and pond sceneries and a strong crystallomantic legacy. It wears this proudly: crystal enchantments are everywhere here, even with a diverse array of different classes taught here. Being such an in-between district has made Windwalk boast a little bit of everything.",
            subPos: { A:[465,242,0,1], B:[465,515,0,1], C:[647,337,-51,1], D:[413,470,-72,1], E:[500,492,0,0], F:[655,470,0,1] },
            subGen: { D: "Class Halls", F: "Residential" },
            subLabel: { A:[-21,0], C:[25,17] },
            subs: [
              { name: "Northside", blurb: "Running north of the main constructed river in the district, Northside has more class halls, more crystallomancy labs, and more faculty residences." },
              { name: "Southside", blurb: "Running south of the main constructed river in the district, Southside has more shops, more magic practice grounds, and more Enforcer presence, since students like to get drunk at the bars that each name themselves after a type of crystal alignment and then start casting spells." },
              { name: "The Havensword Center", blurb: "Starfall’s greatest center of crystallomantic arts, the Havensword family who made their fortune in crystallomancy actually maintain a residence attached to the center and occasionally offer tours" },
            ] },
          { name: "Shatterstar Square", tag: "14", x: 729, y: 418, color: "oklch(0.62 0.085 62)", w: 46,
            blurb: "Shatterstar Square is one of the few districts that survived untouched from before Marquez’s time, said to be too sacred to be damaged in conflict. Rumor has it the blessed star falling on Lumine Field that, in Starfall legend, gave birth to the ley lines and magic in the world, shed its stardust over this district, and the white stone pavers glitter with stardust when you walk on them. With theaters and galleries, Shatterstar Square is firmly a cultural center, although it has a strong Divination legacy as well.",
            subPos: { A:[435,367,0,1], B:[703,505,0,1], C:[500,531,0,1], D:[345,470,0,1], E:[587,209,0,1], F:[655,470,0,1] },
            subGen: { D: "Class Halls", E: "Residential", F: "Class Halls" },
            subLabel: { A:[17,27], E:[-8,0], F:[12,0] },
            subs: [
              { name: "Whisperkeep Library", blurb: "The most renowned library out of many in Starfall, the Whisperkeep Library is filled with too many hidden gems of beautiful, hard-to-reach interior spaces to even name them all." },
              { name: "Cerulean", blurb: "Officially the Cerulean Songbird Center of the Divinatory Arts and Practices, nobody calls it that. Cerulean is a veritable small palace of divination class halls, and it attracts fey presence despite the Academy’s best efforts." },
              { name: "Theater Square", blurb: "A grand boulevard lined with dragonbloom trees, filled with theaters, galleries, museums, and tucked just around the corners from them, street food vendors. Crepes with whisperberry jam are practically a symbol of the district." },
            ] },
          { name: "Stormbringer Way", tag: "15", x: 188, y: 725, color: "oklch(0.55 0.08 248)",
            labelDx: 9, labelDy: 7,
            blurb: "Stormbringer Way stands at the highest point of the Citadel’s western edge, its old stone walls dropping down sharply and overlooking Glimmerdeep. Known as the district of a thousand stairs, it winds sharply on steep elevation changes, a stark contrast between Marveille and Juniper, and it has a strong reputation for illusion magic, minor fey often playing among the ponds that run through the district.",
            subPos: { A:[279,347,0,1], B:[695,232,0,1], C:[621,538,10,1], D:[409,160,0,1], E:[500,492,0,1], F:[690,470,0,1] },
            subGen: { D: "Residential", E: "Class Halls", F: "Commercial" },
            subLabel: { B:[35,0], C:[10,6], D:[-29,-17], E:[-19,35] },
            subs: [
              { name: "Saint Ellen’s Walkway", blurb: "A winding web of pathways that weave through small ponds and the magic plants surrounding them, with powerful illusion magics and small but elegant buildings that are popular for higher-level illusion symposiums." },
              { name: "Lunar Lookout", blurb: "High above the rest of the district, at the top of too many winding stairs, this plaza is ideal for practical divination and for stargazing, with its small park being a popular picnic location if you don’t mind luminis trying to steal your bread." },
              { name: "The Grand Island", blurb: "Named quite ironically, this small inlet juts into the pond that dominates the southern half of the district, with the Everbloom Hall of Illusion and other, smaller class halls on it, small shops running along the perimeter boardwalk." },
            ] },
          { name: "Marquez Plaza", tag: "16", x: 613, y: 760, color: "oklch(0.66 0.085 96)", w: 23,
            blurb: "Marquez Plaza, built in the time of the great hero Headmistress Cecilia Marquez over an old district destroyed in the conflicts, is a stately and beautiful district known for its white marble and crimson lines of pure magic energy that flow through the place in ornamental displays, helping provide a stabilizing foundation for the creation magics that are prominent here. The striking but delicate beauty of the pixie rose flower is the district’s symbol and grows everywhere you look in the same crimson as the characteristic magic flows.",
            subPos: { A:[574,314,0,1], B:[353,357,0,1], C:[578,462,0,1], D:[392,518,0,1], E:[652,423,0,1], F:[323,215,29,1] },
            subGen: { D: "Residential", E: "Class Halls", F: "Commercial" },
            subLabel: { A:[12,0], B:[42,-6], D:[10,0], F:[33,0] },
            subs: [
              { name: "Whisperkeep Observatory", blurb: "A class hall for the divinatory arts with a great enchanted observatory that pierces through light pollution to see the stars as well as if you were out among them. Visiting the Observatory is a rite of passage for diviners even from academies on the other side of the world." },
              { name: "Weaver’s Walk", blurb: "A stately boulevard that runs from the Astral Quarter through all the grandest and most important centers of the district. Weaver’s Walk is technically named for a demon, the ancient Weaver of Grief who assisted Cecilia Marquez, but most people ignore that." },
              { name: "Seerbloom", blurb: "A park filled with rare magical plants of divinatory inclinations, with many small, simple stone constructions hidden behind plants and past waterfall sprays that are perfect to do deep divination work or ley line meditation in." },
            ] },
          { name: "Ravensbeak", tag: "17", x: 162, y: 366, color: "oklch(0.40 0.025 300)", w: -51,
            labelDx: 9, labelDy: 9,
            blurb: "Ravensbeak is a relic of a time of troubled magic confluence when the open skies were dangerous to arcanists, and so the streets are built under raven canopies, magic screens that cast the district in perpetual twilight. Even with the magic confluence resolved, the raven canopies have proven themselves conducive to rare magics, especially summoning and demonology, and the never-ending twilight of the place has become a symbol of that magic and of humanity’s resilience.",
            subPos: { A:[219,370,20,1], B:[500,232,0,1], C:[509,380,0,1], D:[461,498,0,1], E:[500,492,0,0], F:[655,470,0,0] },
            subGen: { D: "Class Halls" },
            subLabel: { A:[0,31], B:[37,12], C:[-50,-12], D:[27,8] },
            subs: [
              { name: "Blackwish", blurb: "You have to pass through a magic curtain to enter this area where the air seems to hold its breath and the interplanar compact is weaker, and a demon could make mental contact with you at any point, allowing clearer communication for the many demonological study centers in the area." },
              { name: "Nightwing Hall", blurb: "Boasting a collection of artifacts that aren’t hexological but still forbidden or dangerous in one way or another, the hall offers looks at artificy you would never find elsewhere." },
              { name: "The Chambers", blurb: "Set in a recessed region in the base of the district, where the light is the dimmest, this area is built around a stately plaza with an illusory rendering of the planes in the center that arcanists can wander through and look closer at, and many high-level summoning and teleportation classes are set here." },
            ] },
          { name: "Garnet District", tag: "18", x: 775, y: 648, color: "oklch(0.50 0.11 25)",
            labelDx: -20, labelDy: -29,
            blurb: "The Garnet District is a classically beautiful district with many overland bridges with tall arches, built around an old viaduct that’s still visible in places, and great warding and counterhexological magic studies, but mostly, it’s known for the Enforcers’ Garrison on the east side.",
            subPos: { A:[669,393,87,1], B:[500,512,0,1], C:[670,250,0,1], D:[392,406,0,1], E:[500,535,0,1], F:[279,153,0,1] },
            subGen: { D: "Commercial", E: "Residential", F: "Class Halls" },
            subLabel: { A:[10,0], B:[-6,10], C:[31,8], D:[-8,0], E:[-12,0], F:[35,0] },
            subs: [
              { name: "Enforcers’ Garrison", blurb: "A complex at the east wall where traditional meets modern, it spills out into the Grounds beyond, with large and involved operations powered by deep magics." },
              { name: "Garnet Hall", blurb: "All roads in the district lead here eventually, a great center for warding and counterhexological magics, with many prospective Enforcers training within these walls." },
              { name: "Gold Dragon", blurb: "Vaguely threatening, given that the eponymous Gold Dragon tried to destroy humanity, this area is nevertheless quite charming, focused on shops and culture and a few rows of townhouses with softly colorful roofs." },
            ] },
          { name: "Seraphim District", tag: "19", x: 760, y: 148, color: "oklch(0.58 0.05 248)", w: -55,
            labelDx: -7, labelDy: -5,
            blurb: "The Seraphim District carves out the glistening and ambitious towers of the northeastern corner of the Citadel, known for teleportation studies and magic symposiums in tower rooms with stunning views of the Grounds. The district is said to be blessed by celestial forces, and was where Magdalena Stonebrook, the first Headmaster after the Founders, is rumored to have first met celestial forces. This is, of course, probably not true, but there is no force more powerful than urban legend.",
            subPos: { A:[513,466,19,1], B:[833,370,0,1], C:[483,160,0,1], D:[345,470,0,1], E:[500,492,0,1], F:[655,470,0,1] },
            subGen: { D: "Residential", E: "Class Halls", F: "Commercial" },
            subLabel: { A:[0,-17], D:[-21,-31], E:[33,10], F:[12,8] },
            subs: [
              { name: "Stonebrook Square", blurb: "The heart of the district centered on a grand plaza with great statuary in celestial designs, every teleporter in Starfall has had a class here at some point, and its roads spiral out to the towers along the edges." },
              { name: "Blessing", blurb: "Running the northeastern edge, Blessing is a beautiful area with stunning views of the cliffs beyond the Citadel, framed by stonework and marble arches overgrown with pink geonium flowers that feed off the ambient magic of spells cast nearby. Naturally, with such a pretty area, you can’t wave a wand without hitting a classy restaurant terrace." },
              { name: "The Great Rook", blurb: "Tall towers in white stone dominate this part of the district, with stunning overlooks of the Grounds below, and people trying teleportation stunts here that often don’t end well." },
            ] },
          { name: "Mercy Square", tag: "20", x: 402, y: 657, color: "oklch(0.46 0.09 18)",
            labelDx: -32, labelDy: 34,
            blurb: "Mercy Square, commanding the center of the Citadel, is known for its two sides: the infirmary on one hand, a beautiful and severe building complex that has saved many arcanists’ lives, lined with gravewood trees among the cool redbrick construction; and the underground spectral rock scene, squeezing for shows into abandoned and forgotten underground or backroom venues. You can find restoration and alchemy magic here, as well as very cheap rent, if you know where to look. And are willing to accept the consequences of why it’s cheap.",
            subPos: { A:[742,314,0,1], B:[500,518,-4,1], C:[670,521,0,1], D:[345,470,0,1], E:[500,538,0,1], F:[323,301,-78,1] },
            subGen: { D: "Class Halls", E: "Commercial", F: "Residential" },
            subLabel: { A:[15,0], F:[-39,0] },
            subs: [
              { name: "The Saints’ Grace Infirmary", blurb: "The dedicated medical center that serves all of Starfall, the Infirmary is always busy, a large complex with solemnly beautiful dark-green landscaping, gravewood trees, and neoclassical colonnades." },
              { name: "Heartcroft", blurb: "This center of underground business, shady backdoor deals, and the best spectral rock performances you’ll find anywhere, in a remarkable display of unsubtlety, is an underground plaza directly underneath the Heartcroft Museum that showcases restoration advances and the advances of the infirmary, a symbol of Mercy Square’s two sides." },
              { name: "The Isadorian Hall of Restoration", blurb: "Starfall’s preeminent center of restoration studies, this grand building greets anyone entering Mercy Square from the Astral Quarter or Marquez Plaza, with statues of old saints and the Great Dolphin herself." },
            ] },
          { name: "Dragoncrest Gardens", tag: "21", x: 500, y: 96, color: "oklch(0.58 0.065 152)",
            labelDx: 0, labelDy: 14,
            blurb: "Dragoncrest Gardens stand at the north center of the Citadel and form the main Citadel entry and exit for those in Boar and Dragon House. Filled with lush hanging-garden style magic greenery, the district is known for herbalism, alchemy, and bestiology studies, and many magic creatures who are allowed inside the wards—especially the fey—call this place home.",
            subPos: { A:[504,252,0,1], B:[721,232,0,1], C:[245,250,0,1], D:[345,470,0,1], E:[500,492,0,1], F:[655,470,0,1] },
            subGen: { D: "Class Halls", E: "Commercial", F: "Residential" },
            subLabel: { A:[-12,10], B:[50,17], C:[31,-4], D:[-8,-19], F:[15,0] },
            subs: [
              { name: "The North Gate", blurb: "The primary entry point for Dragon and Boar students to the Citadel, the North Gate is less grand and less emblematic than the South Gate, but is more recognizable to the students, with its treelined entryway always shimmering with magic." },
              { name: "Prosperia", blurb: "Lush with magical plants and small greenhouses, Prosperia always has something an herbalist might need. And it usually has a small creature or two waiting to try to snatch it from them." },
              { name: "Saint Edna’s", blurb: "This section boasts galleries and botanical gardens, displaying some of the greatest herbological advances in magic, and many herbalism classes are held here." },
            ] },
          // ---- 3 special locations: NOT part of the tessellation — they float
          //      on top of the districts (see app.js), gilded like the Citadel. ----
          { name: "Scorpion House", tag: "✦", special: true, link: ["crescent_district", "A"], x: 556, y: 284,
            blurb: "Art Nouveau halls in the Emberlight Gardens — for artists and lovers." },
          { name: "Cloudless Tower", tag: "✦", special: true, link: ["crescent_district", "E"], x: 447, y: 363,
            blurb: "The clock tower and emblem of the Academy, seen from anywhere in the Citadel." },
          { name: "The Great Hall", tag: "✦", special: true, link: ["dragon_s_walk", "A"], x: 512, y: 979,
            blurb: "Where students gather each morning for breakfast, announcements and scheming." },
          { name: "The Infirmary", tag: "✦", special: true, link: ["mercy_square", "A"], x: 450, y: 574,
            blurb: "At the easternmost point of Mercy Square — wards, healers and the long convalescence halls." },
          { name: "Enforcers’ Garrison", tag: "✦", special: true, link: ["garnet_district", "A"], x: 872, y: 688,
            blurb: "On the eastern edge of the Garnet District — barracks and muster of the Citadel’s wardens." },
        ],
      },
    },
  ];

  window.STARFALL_REGIONS = REGIONS;
})();
